"use client";

import { useState, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { 
  Github, 
  Download, 
  RefreshCw, 
  Palette,
  Grid3X3,
  Heart,
  Star,
  Zap,
  Music,
  Coffee,
  Code,
  Book,
  Gamepad2,
  Rocket,
  Cat,
  Dog,
  Bird,
  Fish,
  TreePine,
  Flower,
  Sun,
  Moon,
  Cloud,
  Rainbow,
  Flame,
  Droplets,
  Snowflake,
  Mountain,
  Waves,
  Camera,
  Film,
  Paintbrush,
  Pencil,
  Lightbulb,
  Target,
  Trophy,
  Medal,
  Crown,
  Gem,
  Key,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Bell,
  Settings,
  User,
  Users,
  Home,
  Map,
  Compass,
  Navigation,
  Plane,
  Train,
  Car,
  Bike,
  Footprints,
  Clock,
  Calendar,
  Mail,
  Phone,
  MessageCircle,
  Send,
  Share2,
  Link,
  Paperclip,
  FileText,
  Folder,
  Image,
  Video,
  Music2,
  Mic,
  Volume2,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Mouse,
  Keyboard,
  Printer,
  Wifi,
  Bluetooth,
  Battery,
  Plug,
  ZapIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  Umbrella,
  Thermometer,
  Wind,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Tornado,
  Earth,
  Globe,
  MapPin,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Bitcoin,
  CreditCard,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Gift,
  PartyPopper,
  Sparkles,
  HeartIcon,
  StarIcon,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Annoyed,
  Angry,
  AlertCircle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Info,
  AlertTriangle,
  Shield,
  ShieldCheck,
  ShieldAlert,
  LockIcon,
  UnlockIcon,
  KeyIcon,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  CheckSquare,
  MinusSquare,
  PlusSquare,
  Trash2,
  Edit,
  Copy,
  Scissors,
  Clipboard,
  Save,
  Upload,
  DownloadIcon,
  ExternalLink,
  Maximize,
  Minimize,
  Move,
  RotateCcw,
  RotateCw,
  Undo,
  Redo,
  RefreshCcw,
  Repeat,
  Shuffle,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  VolumeX,
  Volume1,
  Volume,
  Cast,
  Airplay,
  Chromecast,
  Rss,
  WifiOff,
  Signal,
  BatteryLow,
  BatteryMedium,
  BatteryFull,
  BatteryCharging,
  Power,
  PowerOff,
  Moon2,
  SunDim,
  Sunrise,
  Sunset,
  Cloudy,
  CloudFog,
  CloudHail,
  CloudDrizzle,
  Snowflake2,
  ThermometerSun,
  ThermometerSnowflake,
  Droplet,
  WavesIcon,
  FlameIcon,
  Bomb,
  Ghost,
  Skull,
  Alien,
  RocketIcon,
  Satellite,
  Telescope,
  Microscope,
  GraduationCap,
  School,
  Library,
  BookOpen,
  BookX,
  BookmarkIcon,
  Glasses,
  Sunglasses,
  Shirt,
  ShoppingBasket,
  Store,
  Building,
  Building2,
  Factory,
  Warehouse,
  Hospital,
  Banknote,
  Landmark,
  Church,
  Castle,
  Tent,
  TreeDeciduous,
  TreePineIcon,
  Flower2,
  Leaf,
  Sprout,
  Seedling,
  Recycle,
  Trash,
  TrashIcon,
  Delete,
  Eraser,
  PenTool,
  Brush,
  PaintBucket,
  PaletteIcon,
  Pipette,
  Blend,
  Layers,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Table,
  Grid,
  Columns,
  Rows,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  Menu,
  MoreHorizontal,
  MoreVertical,
  GripVertical,
  GripHorizontal,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftUp,
  CornerLeftDown,
  CornerRightUp,
  CornerRightDown,
  Expand,
  Shrink,
  Maximize2,
  Minimize2,
  MoveIcon,
  MoveHorizontal,
  MoveVertical,
  MoveDiagonal,
  MoveDiagonal2,
  Select,
  Selection,
  Frame,
  Crop,
  Slice,
  ScissorsIcon,
  Divide,
  DivideSquare,
  DivideCircle,
  Ratio,
  Proportions,
  Scale,
  Ruler,
  CompassIcon,
  Square,
  Circle,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Diamond,
  Heart2,
  Star2,
  Sparkle,
  Zap2,
  Flame2,
  Droplets2,
  Snowflake3,
  Cloud2,
  Sun2,
  Moon3,
  Rainbow2,
  Umbrella2,
  GlassWater,
  Mug,
  Wine,
  Beer,
  CoffeeIcon,
  Pizza,
  Hamburger,
  IceCream,
  Cookie,
  Candy,
  Apple,
  Banana,
  Cherry,
  Grape,
  Citrus,
  Carrot,
  Salad,
  Soup,
  Utensils,
  ForkKnife,
  Plate,
  ChefHat,
  Microwave,
  Oven,
  Refrigerator,
  WashingMachine,
  Dryer,
  Vacuum,
  Fan,
  AirVent,
  Heater,
  Thermostat,
  LightbulbIcon,
  Lamp,
  LampFloor,
  LampDesk,
  Flashlight,
  Candle,
  FireExtinguisher,
  Siren,
  AlarmCheck,
  AlarmClock,
  AlarmClockOff,
  Timer,
  TimerOff,
  TimerReset,
  Hourglass,
  History,
  RotateCcwIcon,
  RotateCwIcon,
  Undo2,
  Redo2,
  Reply,
  ReplyAll,
  Forward,
  MailOpen,
  MailWarning,
  MailCheck,
  MailX,
  MailQuestion,
  MailPlus,
  MailMinus,
  Inbox,
  Archive,
  ArchiveX,
  ArchiveRestore,
  Trash3,
  File,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileQuestion,
  FileWarning,
  FileCode,
  FileJson,
  FileType,
  FileSpreadsheet,
  FilePieChart,
  FileBarChart,
  FileAudio,
  FileVideo,
  FileImage,
  FileTextIcon,
  FileArchive,
  FileUp,
  FileDown,
  FileClock,
  FileSearch,
  FileKey,
  FileLock,
  FileHeart,
  FileCog,
  Files,
  FolderIcon,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderCheck,
  FolderX,
  FolderSearch,
  FolderHeart,
  FolderCog,
  FolderGit,
  FolderGit2,
  FolderKanban,
  FolderTree,
  FolderArchive,
  FolderRoot,
  HardDrive,
  Database,
  Server,
  ServerOff,
  ServerCrash,
  CloudServer,
  CloudCog,
  CloudDownload,
  CloudUpload,
  CloudOff,
  DatabaseBackup,
  DatabaseZap,
  Table2,
  Grid2X2,
  Grid3X3Icon,
  LayoutDashboard,
  LayoutPanelLeft,
  LayoutPanelTop,
  Kanban,
  KanbanSquare,
  ListTodo,
  ListChecks,
  ListX,
  ListStart,
  ListEnd,
  ListMusic,
  ListVideo,
  ListOrderedIcon,
  ListCollapse,
  Indent,
  Outdent,
  Text,
  TextSelect,
  TextQuote,
  WrapText,
  Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  CaseSensitive,
  CaseLower,
  CaseUpper,
  RemoveFormatting,
  Superscript,
  Subscript,
  UnderlineIcon,
  StrikethroughIcon,
  Overline,
  Quote,
  CodeIcon,
  Code2,
  TerminalIcon,
  TerminalSquare,
  CurlyBraces,
  Brackets,
  Parentheses,
  Command,
  Option,
  Control,
  Shift,
  Capslock,
  Backspace,
  DeleteIcon,
  Enter,
  Escape,
  PageUp,
  PageDown,
  HomeIcon,
  End,
  ArrowBigUp,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUpDash,
  ArrowBigDownDash,
  ArrowBigLeftDash,
  ArrowBigRightDash,
  CircleDot,
  CircleDashed,
  CircleSlash,
  CircleOff,
  CircleEqual,
  CircleDivide,
  CircleX,
  CircleCheck,
  CircleCheckBig,
  CircleAlert,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CircleStop,
  CircleSkipBack,
  CircleSkipForward,
  CircleChevronUp,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleArrowUp,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowRight,
  SquareIcon,
  SquareDashed,
  SquareDot,
  SquareSlash,
  SquareEqual,
  SquareDivide,
  SquareX,
  SquareCheck,
  SquareCheckBig,
  SquareAlert,
  SquareHelp,
  SquarePause,
  SquarePlay,
  SquareStop,
  SquareSkipBack,
  SquareSkipForward,
  SquareChevronUp,
  SquareChevronDown,
  SquareChevronLeft,
  SquareChevronRight,
  SquareArrowUp,
  SquareArrowDown,
  SquareArrowLeft,
  SquareArrowRight,
  OctagonIcon,
  OctagonAlert,
  OctagonX,
  OctagonPause,
  TriangleIcon,
  TriangleAlert,
  PentagonIcon,
  HexagonIcon,
  DiamondIcon,
  Trapezoid,
  Parallelogram,
  Cylinder,
  Cone,
  Cube,
  Box,
  PackageIcon,
  PackageOpen,
  PackageCheck,
  PackageX,
  PackageSearch,
  PackagePlus,
  PackageMinus,
  Container,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  StoreIcon,
  BuildingIcon,
  Building2Icon,
  FactoryIcon,
  WarehouseIcon,
  HospitalIcon,
  BanknoteIcon,
  LandmarkIcon,
  ChurchIcon,
  CastleIcon,
  TentIcon,
  TreeDeciduousIcon,
  TreePineIcon2,
  Flower2Icon,
  LeafIcon,
  SproutIcon,
  SeedlingIcon,
  RecycleIcon,
  TrashIcon2,
  DeleteIcon,
  EraserIcon,
  PenToolIcon,
  BrushIcon,
  PaintBucketIcon,
  PaletteIcon2,
  PipetteIcon,
  BlendIcon,
  LayersIcon,
  LayoutIcon,
  LayoutGridIcon,
  LayoutListIcon,
  LayoutTemplateIcon,
  TableIcon,
  GridIcon,
  ColumnsIcon,
  RowsIcon,
  PanelLeftIcon,
  PanelRightIcon,
  PanelTopIcon,
  PanelBottomIcon,
  SidebarIcon,
  SidebarCloseIcon,
  SidebarOpenIcon,
  MenuIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  GripVerticalIcon,
  GripHorizontalIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpIcon,
  ChevronsDownIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  CornerDownLeftIcon,
  CornerDownRightIcon,
  CornerLeftUpIcon,
  CornerLeftDownIcon,
  CornerRightUpIcon,
  CornerRightDownIcon,
  ExpandIcon,
  ShrinkIcon,
  MaximizeIcon,
  MinimizeIcon,
  MoveIcon2,
  MoveHorizontalIcon,
  MoveVerticalIcon,
  MoveDiagonalIcon,
  MoveDiagonal2Icon,
  SelectIcon,
  SelectionIcon,
  FrameIcon,
  CropIcon,
  SliceIcon,
  ScissorsIcon2,
  DivideIcon,
  DivideSquareIcon,
  DivideCircleIcon,
  RatioIcon,
  ProportionsIcon,
  ScaleIcon,
  RulerIcon,
  CompassIcon2,
  SquareIcon2,
  CircleIcon,
  TriangleIcon2,
  PentagonIcon2,
  HexagonIcon2,
  OctagonIcon2,
  DiamondIcon2,
  HeartIcon2,
  StarIcon2,
  SparkleIcon,
  ZapIcon2,
  FlameIcon2,
  DropletsIcon2,
  SnowflakeIcon2,
  CloudIcon2,
  SunIcon2,
  MoonIcon2,
  RainbowIcon2,
  UmbrellaIcon2,
  GlassWaterIcon,
  MugIcon,
  WineIcon,
  BeerIcon,
  CoffeeIcon2,
  PizzaIcon,
  HamburgerIcon,
  IceCreamIcon,
  CookieIcon,
  CandyIcon,
  AppleIcon,
  BananaIcon,
  CherryIcon,
  GrapeIcon,
  CitrusIcon,
  CarrotIcon,
  SaladIcon,
  SoupIcon,
  UtensilsIcon,
  ForkKnifeIcon,
  PlateIcon,
  ChefHatIcon,
  MicrowaveIcon,
  OvenIcon,
  RefrigeratorIcon,
  WashingMachineIcon,
  DryerIcon,
  VacuumIcon,
  FanIcon,
  AirVentIcon,
  HeaterIcon,
  ThermostatIcon,
  LightbulbIcon2,
  LampIcon,
  LampFloorIcon,
  LampDeskIcon,
  FlashlightIcon,
  CandleIcon,
  FireExtinguisherIcon,
  SirenIcon,
  AlarmCheckIcon,
  AlarmClockIcon,
  AlarmClockOffIcon,
  TimerIcon,
  TimerOffIcon,
  TimerResetIcon,
  HourglassIcon,
  HistoryIcon,
  RotateCcwIcon2,
  RotateCwIcon2,
  UndoIcon,
  RedoIcon,
  ReplyIcon,
  ReplyAllIcon,
  ForwardIcon,
  MailOpenIcon,
  MailWarningIcon,
  MailCheckIcon,
  MailXIcon,
  MailQuestionIcon,
  MailPlusIcon,
  MailMinusIcon,
  InboxIcon,
  ArchiveIcon,
  ArchiveXIcon,
  ArchiveRestoreIcon,
  Trash3Icon,
  FileIcon,
  FilePlusIcon,
  FileMinusIcon,
  FileCheckIcon,
  FileXIcon,
  FileQuestionIcon,
  FileWarningIcon,
  FileCodeIcon,
  FileJsonIcon,
  FileTypeIcon,
  FileSpreadsheetIcon,
  FilePieChartIcon,
  FileBarChartIcon,
  FileAudioIcon,
  FileVideoIcon,
  FileImageIcon,
  FileTextIcon2,
  FileArchiveIcon,
  FileUpIcon,
  FileDownIcon,
  FileClockIcon,
  FileSearchIcon,
  FileKeyIcon,
  FileLockIcon,
  FileHeartIcon,
  FileCogIcon,
  FilesIcon,
  FolderIcon2,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderMinusIcon,
  FolderCheckIcon,
  FolderXIcon,
  FolderSearchIcon,
  FolderHeartIcon,
  FolderCogIcon,
  FolderGitIcon,
  FolderGit2Icon,
  FolderKanbanIcon,
  FolderTreeIcon,
  FolderArchiveIcon,
  FolderRootIcon,
  HardDriveIcon,
  DatabaseIcon,
  ServerIcon,
  ServerOffIcon,
  ServerCrashIcon,
  CloudServerIcon,
  CloudCogIcon,
  CloudDownloadIcon,
  CloudUploadIcon,
  CloudOffIcon,
  DatabaseBackupIcon,
  DatabaseZapIcon,
  Table2Icon,
  Grid2X2Icon,
  Grid3X3Icon2,
  LayoutDashboardIcon,
  LayoutPanelLeftIcon,
  LayoutPanelTopIcon,
  KanbanIcon,
  KanbanSquareIcon,
  ListTodoIcon,
  ListChecksIcon,
  ListXIcon,
  ListStartIcon,
  ListEndIcon,
  ListMusicIcon,
  ListVideoIcon,
  ListOrderedIcon2,
  ListCollapseIcon,
  IndentIcon,
  OutdentIcon,
  TextIcon,
  TextSelectIcon,
  TextQuoteIcon,
  WrapTextIcon,
  PilcrowIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  Heading4Icon,
  Heading5Icon,
  Heading6Icon,
  CaseSensitiveIcon,
  CaseLowerIcon,
  CaseUpperIcon,
  RemoveFormattingIcon,
  SuperscriptIcon,
  SubscriptIcon,
  UnderlineIcon2,
  StrikethroughIcon2,
  OverlineIcon,
  QuoteIcon,
  CodeIcon2,
  Code2Icon,
  TerminalIcon2,
  TerminalSquareIcon,
  CurlyBracesIcon,
  BracketsIcon,
  ParenthesesIcon,
  CommandIcon,
  OptionIcon,
  ControlIcon,
  ShiftIcon,
  CapslockIcon,
  BackspaceIcon,
  DeleteIcon2,
  EnterIcon,
  EscapeIcon,
  PageUpIcon,
  PageDownIcon,
  HomeIcon2,
  EndIcon,
  ArrowBigUpIcon,
  ArrowBigDownIcon,
  ArrowBigLeftIcon,
  ArrowBigRightIcon,
  ArrowBigUpDashIcon,
  ArrowBigDownDashIcon,
  ArrowBigLeftDashIcon,
  ArrowBigRightDashIcon,
  CircleDotIcon,
  CircleDashedIcon,
  CircleSlashIcon,
  CircleOffIcon,
  CircleEqualIcon,
  CircleDivideIcon,
  CircleXIcon,
  CircleCheckIcon,
  CircleCheckBigIcon,
  CircleAlertIcon,
  CircleHelpIcon,
  CirclePauseIcon,
  CirclePlayIcon,
  CircleStopIcon,
  CircleSkipBackIcon,
  CircleSkipForwardIcon,
  CircleChevronUpIcon,
  CircleChevronDownIcon,
  CircleChevronLeftIcon,
  CircleChevronRightIcon,
  CircleArrowUpIcon,
  CircleArrowDownIcon,
  CircleArrowLeftIcon,
  CircleArrowRightIcon,
  SquareIcon3,
  SquareDashedIcon,
  SquareDotIcon,
  SquareSlashIcon,
  SquareEqualIcon,
  SquareDivideIcon,
  SquareXIcon,
  SquareCheckIcon,
  SquareCheckBigIcon,
  SquareAlertIcon,
  SquareHelpIcon,
  SquarePauseIcon,
  SquarePlayIcon,
  SquareStopIcon,
  SquareSkipBackIcon,
  SquareSkipForwardIcon,
  SquareChevronUpIcon,
  SquareChevronDownIcon,
  SquareChevronLeftIcon,
  SquareChevronRightIcon,
  SquareArrowUpIcon,
  SquareArrowDownIcon,
  SquareArrowLeftIcon,
  SquareArrowRightIcon,
  OctagonIcon3,
  OctagonAlertIcon,
  OctagonXIcon,
  OctagonPauseIcon,
  TriangleIcon3,
  TriangleAlertIcon,
  PentagonIcon3,
  HexagonIcon3,
  DiamondIcon3,
  TrapezoidIcon,
  ParallelogramIcon,
  CylinderIcon,
  ConeIcon,
  CubeIcon,
  BoxIcon,
  PackageIcon2,
  PackageOpenIcon,
  PackageCheckIcon,
  PackageXIcon,
  PackageSearchIcon,
  PackagePlusIcon,
  PackageMinusIcon,
  ContainerIcon,
} from "lucide-react";

const icons = [
  Heart, Star, Zap, Music, Coffee, Code, Book, Gamepad2, Rocket,
  Cat, Dog, Bird, Fish, TreePine, Flower, Sun, Moon, Cloud, Rainbow,
  Flame, Droplets, Snowflake, Mountain, Waves, Camera, Film, Paintbrush,
  Pencil, Lightbulb, Target, Trophy, Medal, Crown, Gem, Key, Lock,
  Github, Download, RefreshCw, Palette, Grid3X3,
];

const patterns = {
  heart: [
    [0,1,0,1,0],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [0,1,1,1,0],
    [0,0,1,0,0],
  ],
  star: [
    [0,0,1,0,0],
    [0,1,1,1,0],
    [1,1,1,1,1],
    [0,1,1,1,0],
    [1,0,1,0,1],
  ],
  smiley: [
    [0,1,1,1,0],
    [1,0,0,0,1],
    [1,0,1,0,1],
    [1,1,0,1,1],
    [0,1,1,1,0],
  ],
  rocket: [
    [0,0,1,0,0],
    [0,1,1,1,0],
    [1,1,1,1,1],
    [1,0,1,0,1],
    [0,1,0,1,0],
  ],
  tree: [
    [0,0,1,0,0],
    [0,1,1,1,0],
    [1,1,1,1,1],
    [0,0,1,0,0],
    [0,0,1,0,0],
  ],
  house: [
    [0,0,1,0,0],
    [0,1,1,1,0],
    [1,1,1,1,1],
    [1,0,1,0,1],
    [1,1,1,1,1],
  ],
  letterN: [
    [1,0,0,0,1],
    [1,1,0,0,1],
    [1,0,1,0,1],
    [1,0,0,1,1],
    [1,0,0,0,1],
  ],
  letterE: [
    [1,1,1,1,1],
    [1,0,0,0,0],
    [1,1,1,1,0],
    [1,0,0,0,0],
    [1,1,1,1,1],
  ],
  letterM: [
    [1,0,0,0,1],
    [1,1,0,1,1],
    [1,0,1,0,1],
    [1,0,0,0,1],
    [1,0,0,0,1],
  ],
  letterO: [
    [0,1,1,1,0],
    [1,0,0,0,1],
    [1,0,0,0,1],
    [1,0,0,0,1],
    [0,1,1,1,0],
  ],
};

export function GitHubContributionArt() {
  const [selectedPattern, setSelectedPattern] = useState<keyof typeof patterns>("heart");
  const [selectedIcon, setSelectedIcon] = useState(icons[0]);
  const [intensity, setIntensity] = useState([2, 3, 4]);
  const [grid, setGrid] = useState<number[][]>([]);
  const [yearOffset, setYearOffset] = useState(0);

  const generateGrid = useCallback(() => {
    const pattern = patterns[selectedPattern];
    const newGrid: number[][] = [];
    
    // Generate 7 rows (days of week) x 53 columns (weeks in year)
    for (let row = 0; row < 7; row++) {
      const gridRow: number[] = [];
      for (let col = 0; col < 53; col++) {
        // Map pattern to grid
        const patternRow = Math.floor((row / 7) * pattern.length);
        const patternCol = Math.floor((col / 53) * pattern[0].length);
        
        if (pattern[patternRow]?.[patternCol]) {
          // Random intensity for pattern cells
          gridRow.push(intensity[Math.floor(Math.random() * intensity.length)]);
        } else {
          // Random low activity for non-pattern cells
          gridRow.push(Math.random() > 0.7 ? 1 : 0);
        }
      }
      newGrid.push(gridRow);
    }
    
    setGrid(newGrid);
  }, [selectedPattern, intensity]);

  useEffect(() => {
    generateGrid();
  }, [generateGrid]);

  const getCellColor = (value: number) => {
    const colors = [
      "bg-muted",
      "bg-emerald-200 dark:bg-emerald-900",
      "bg-emerald-300 dark:bg-emerald-700",
      "bg-emerald-400 dark:bg-emerald-600",
      "bg-emerald-500 dark:bg-emerald-500",
    ];
    return colors[value] || colors[0];
  };

  const downloadAsImage = () => {
    const canvas = document.createElement("canvas");
    canvas.width = 800;
    canvas.height = 150;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const cellSize = 12;
    const gap = 2;

    grid.forEach((row, rowIndex) => {
      row.forEach((cell, colIndex) => {
        const colors = ["#e5e7eb", "#86efac", "#4ade80", "#22c55e", "#16a34a"];
        ctx.fillStyle = colors[cell] || colors[0];
        ctx.fillRect(
          colIndex * (cellSize + gap),
          rowIndex * (cellSize + gap),
          cellSize,
          cellSize
        );
      });
    });

    const link = document.createElement("a");
    link.download = `github-contribution-art-${selectedPattern}.png`;
    link.href = canvas.toDataURL();
    link.click();
  };

  const copyToClipboard = () => {
    const text = grid.map(row => row.join(",")).join("\n");
    navigator.clipboard.writeText(text);
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-6 rounded-2xl border border-border bg-card">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <Github className="h-5 w-5" />
          <h3 className="text-lg font-semibold">GitHub Contribution Art Generator</h3>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={copyToClipboard}>
            Copy Data
          </Button>
          <Button size="sm" onClick={downloadAsImage}>
            <Download className="h-4 w-4 mr-1" />
            Download
          </Button>
        </div>
      </div>

      {/* Controls */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div>
          <label className="text-sm font-medium mb-2 block">Pattern</label>
          <div className="grid grid-cols-5 gap-1">
            {(Object.keys(patterns) as Array<keyof typeof patterns>).map((pattern) => (
              <button
                key={pattern}
                onClick={() => setSelectedPattern(pattern)}
                className={`p-2 rounded border text-xs capitalize transition-colors ${
                  selectedPattern === pattern
                    ? "bg-primary text-primary-foreground border-primary"
                    : "bg-muted hover:bg-muted/80 border-border"
                }`}
              >
                {pattern}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="text-sm font-medium mb-2 block">Intensity</label>
          <div className="flex gap-2">
            {[1, 2, 3, 4].map((level) => (
              <button
                key={level}
                onClick={() => setIntensity([level])}
                className={`w-8 h-8 rounded ${getCellColor(level)} ${
                  intensity.includes(level) ? "ring-2 ring-primary" : ""
                }`}
              />
            ))}
          </div>
        </div>

        <div>
          <label className="text-sm font-medium mb-2 block">Actions</label>
          <Button onClick={generateGrid} variant="outline" className="w-full">
            <RefreshCw className="h-4 w-4 mr-1" />
            Regenerate
          </Button>
        </div>
      </div>

      {/* Grid */}
      <div className="overflow-x-auto">
        <div className="inline-block min-w-full p-4 rounded-xl bg-muted/50">
          <div className="flex gap-1">
            {grid[0]?.map((_, colIndex) => (
              <div key={colIndex} className="flex flex-col gap-1">
                {grid.map((row, rowIndex) => (
                  <motion.div
                    key={rowIndex}
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: (colIndex * 7 + rowIndex) * 0.001 }}
                    className={`w-3 h-3 rounded-sm ${getCellColor(row[colIndex])}`}
                  />
                ))}
              </div>
            ))}
          </div>
          
          <div className="flex justify-between mt-2 text-xs text-muted-foreground">
            <span>Jan</span>
            <span>Feb</span>
            <span>Mar</span>
            <span>Apr</span>
            <span>May</span>
            <span>Jun</span>
            <span>Jul</span>
            <span>Aug</span>
            <span>Sep</span>
            <span>Oct</span>
            <span>Nov</span>
            <span>Dec</span>
          </div>
        </div>
      </div>

      <p className="text-sm text-muted-foreground mt-4 text-center">
        This generates a pattern that mimics GitHub&apos;s contribution graph.
        Use it as inspiration for your actual coding schedule! 💪
      </p>
    </div>
  );
}
